Repository MyCityOrganization/MyCityRemoteRepo, pull requests merged in 2025-05, with the labels that each got.

#77 Events functionality
  admin-service/src/main/java/com/mycity/admin/config/SecurityConfig.java
  admin-service/src/main/java/com/mycity/admin/controller/AdminEventController.java
  api-gateway/src/main/java/com/mycity/apigateway/config/JwtAuthFilter.java
  client-service/src/main/java/com/mycity/client/event/ClientEventController.java
  client-service/src/main/java/com/mycity/client/tripplanner/ClientTripRequestController.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/controller/EventsPlaceController.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/entity/Event.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/entity/EventHighlights.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/exception/EventsPlaceException.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/repository/EventsRepository.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/service/EventsPlaceServiceInterface.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/serviceImpl/EventsPlaceService.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/serviceImpl/MediaServiceConfig.java
  eventsplace-service/src/main/resources/application.properties
  media-service/src/main/java/com/mycity/media/config/SecurityConfig.java
  media-service/src/main/java/com/mycity/media/controller/EventImageController.java
  media-service/src/main/java/com/mycity/media/repository/EventSubImagesRepository.java
  media-service/src/main/java/com/mycity/media/service/EventImageService.java
  media-service/src/main/java/com/mycity/media/serviceImpl/EventImageServiceImpl.java
  media-service/src/main/resources/application.properties
  mycity-common-dtos/src/main/java/com/mycity/shared/eventsdto/EventCardDto.java
  mycity-common-dtos/src/main/java/com/mycity/shared/eventsdto/EventHighlightsDTO.java
  mycity-common-dtos/src/main/java/com/mycity/shared/eventsdto/EventsDTO.java
  mycity-common-dtos/src/main/java/com/mycity/shared/mediadto/EventSubImagesDTO.java
Labels: bug, enhancement, good first issue

#83 Optimized the code and added features such as Media images fetching for category and place services
  api-gateway/src/main/java/com/mycity/apigateway/config/GatewaySecurityConfig.java
  categoryplace-service/src/main/java/com/mycity/category/controller/CategoryController.java
  categoryplace-service/src/main/java/com/mycity/category/exception/GlobalExceptionHandler.java
  categoryplace-service/src/main/java/com/mycity/category/serviceImpl/CategoryServiceImpl.java
  client-service/src/main/java/com/mycity/client/category/ClientCategoryController.java
  eventsplace-service/src/main/java/com/mycity/eventsplace/serviceImpl/EventsPlaceService.java
  media-service/src/main/java/com/mycity/media/config/WebClientConfig.java
  media-service/src/main/java/com/mycity/media/controller/ImageController.java
  media-service/src/main/java/com/mycity/media/service/ImageService.java
  media-service/src/main/java/com/mycity/media/serviceImpl/ImageServiceImpl.java
  mycity-common-dtos/src/main/java/com/mycity/shared/placedto/PlaceCategoryDTO.java
  place-service/src/main/java/com/mycity/place/controller/PlaceController.java
Labels: documentation, enhancement, good first issue

#88 Updated The Category Service PlaceByCategories
  categoryplace-service/src/main/java/com/mycity/category/controller/CategoryController.java
  categoryplace-service/src/main/java/com/mycity/category/repository/CategoryRepository.java
  categoryplace-service/src/main/java/com/mycity/category/service/CategoryService.java
  categoryplace-service/src/main/java/com/mycity/category/serviceImpl/CategoryServiceImpl.java
  categoryplace-service/src/main/java/com/mycity/category/serviceImpl/WebClientMediaService.java
  categoryplace-service/src/main/java/com/mycity/category/serviceImpl/WebClientPlaceService.java
  categoryplace-service/src/main/resources/application.properties
  client-service/src/main/java/com/mycity/client/category/ClientCategoryController.java
  client-service/src/main/java/com/mycity/client/serviceImpl/ClientCategoryService.java
  media-service/src/main/java/com/mycity/media/config/MediaSecurityConfig.java
  media-service/src/main/java/com/mycity/media/controller/ImageController.java
  media-service/src/main/java/com/mycity/media/repository/ImageServiceRepository.java
  media-service/src/main/java/com/mycity/media/service/ImageService.java
  media-service/src/main/java/com/mycity/media/serviceImpl/ImageServiceImpl.java
  mycity-common-dtos/src/main/java/com/mycity/shared/categorydto/CategoryWithPlacesDTO.java
  mycity-common-dtos/src/main/java/com/mycity/shared/placedto/PlaceRelatedImagesDTO.java
  place-service/src/main/java/com/mycity/place/config/SecurityConfig.java
  place-service/src/main/java/com/mycity/place/controller/PlaceController.java
  place-service/src/main/java/com/mycity/place/repository/PlaceRepository.java
  place-service/src/main/java/com/mycity/place/service/PlaceServiceInterface.java
  place-service/src/main/java/com/mycity/place/serviceImpl/PlaceServiceImpl.java
Labels: enhancement, good first issue

#91 Updated the placeserviceImplTest and also resolved bug where placediscoveries are commented and also resolved the merge conflicts
  admin-service/pom.xml
  admin-service/src/main/java/com/mycity/admin/controller/AdminPlaceController.java
  media-service/src/main/java/com/mycity/media/controller/ImageController.java
  place-service/src/main/java/com/mycity/place/controller/PlaceController.java
  place-service/src/main/java/com/mycity/place/serviceImpl/AboutPlaceDetailServiceImpl.java
  place-service/src/main/java/com/mycity/place/serviceImpl/PlaceDiscoveriesServiceimpl.java
  place-service/src/main/java/com/mycity/place/serviceImpl/WebClientMediaService.java
  place-service/src/test/java/com/mycity/place/test/PlaceControllerTest.java
  place-service/src/test/java/com/mycity/place/test/PlaceServiceImplTest.java
Labels: bug, enhancement, good first issue
